# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 02:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='参与时间')),
                ('is_done', models.BooleanField(default=False, help_text='是否已经完成')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名称', help_text='客户名称', max_length=32)),
                ('email', models.EmailField(blank=True, default='', help_text='邮箱', max_length=254, null=True)),
                ('company', models.CharField(blank=True, default='', help_text='公司名称', max_length=32, null=True)),
                ('address', models.CharField(blank=True, default='', help_text='地址', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='手机号码', max_length=16, null=True)),
                ('mobile', models.CharField(blank=True, default='', help_text='座机', max_length=16, null=True)),
                ('qq', models.CharField(blank=True, default='', help_text='QQ', max_length=16, null=True)),
                ('wechat', models.CharField(blank=True, default='', help_text='微信号', max_length=64, null=True)),
                ('web', models.CharField(blank=True, default='', help_text='网站地址', max_length=64, null=True)),
                ('industry', models.CharField(blank=True, default='', help_text='行业', max_length=32, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='公司简介', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=8)),
                ('description', models.TextField(default='', help_text='介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='余额')),
            ],
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发生时间')),
                ('quantity', models.IntegerField(default=0, help_text='数量')),
                ('reason', models.CharField(help_text='变动原因', max_length=32)),
                ('direction', models.BooleanField(default=True, help_text='方向,增加为True,减少为False')),
                ('point', models.ForeignKey(help_text='积分', on_delete=django.db.models.deletion.CASCADE, to='myApp.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='题纲', max_length=128)),
                ('index', models.IntegerField(db_index=True, default=0, help_text='题目题号')),
                ('category', models.CharField(choices=[('radio', '单选'), ('select', '多选')], default='radio', help_text='是否多选', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='选项内容', max_length=32)),
                ('question', models.ForeignKey(help_text='题目', on_delete=django.db.models.deletion.CASCADE, to='myApp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', help_text='标题', max_length=64)),
                ('create_date', models.DateTimeField(help_text='创建时间')),
                ('deadline', models.DateTimeField(help_text='截止时间')),
                ('state', models.IntegerField(default=0, help_text='状态,0-->草稿,1-->待审核,2-->审核失败,\n                                                        3-->审核成功,4-->发布成功')),
                ('quantity', models.IntegerField(default=1, help_text='发布数量')),
                ('free_count', models.IntegerField(default=1, help_text='可用问卷数量')),
                ('customer', models.ForeignKey(help_text='客户信息', on_delete=django.db.models.deletion.CASCADE, to='myApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='审核时间')),
                ('comment', models.TextField(help_text='审核批注')),
                ('questionnaire', models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='myApp.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='提交时间')),
                ('comment', models.TextField(default='', help_text='建议内容')),
                ('questionnaire', models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='myApp.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ShareHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='分享时间')),
                ('url', models.CharField(blank=True, default='', help_text='分享链接', max_length=128, null=True)),
                ('qrcode', models.CharField(blank=True, help_text='分享二维码', max_length=32, null=True)),
                ('questionnaire', models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='myApp.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='SignHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='签到时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='姓名', help_text='姓名', max_length=32)),
                ('age', models.IntegerField(default=1, help_text='年龄')),
                ('gender', models.BooleanField(default='male', help_text='性别')),
                ('phone', models.CharField(blank=True, default='', help_text='手机号码', max_length=16, null=True)),
                ('email', models.EmailField(blank=True, default='', help_text='邮箱', max_length=254, null=True)),
                ('address', models.CharField(blank=True, default='', help_text='地址', max_length=256, null=True)),
                ('birthday', models.DateField(default=datetime.date(2018, 1, 1), help_text='出生日期', null=True)),
                ('qq', models.CharField(blank=True, default='', help_text='QQ', max_length=16, null=True)),
                ('wechat', models.CharField(blank=True, default='', help_text='微信号', max_length=64, null=True)),
                ('job', models.CharField(blank=True, default='', help_text='职业', max_length=32, null=True)),
                ('interest', models.TextField(blank=True, default='', help_text='兴趣爱好', null=True)),
                ('salary', models.CharField(blank=True, default='', help_text='收入水平', max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='余额')),
                ('customer', models.OneToOneField(help_text='客户', on_delete=django.db.models.deletion.CASCADE, to='myApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='WalletFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='发生金额')),
                ('direction', models.BooleanField(default=True, help_text='方向,增加为True,减少为False')),
                ('create_date', models.DateTimeField(auto_now=True, help_text='发生时间')),
                ('reason', models.CharField(help_text='变动原因', max_length=32)),
                ('done', models.BooleanField(default=False, help_text='是否已完成')),
                ('payment', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], help_text='支付方式', max_length=32)),
                ('paymentid', models.CharField(help_text='第三方支付id', max_length=128)),
                ('wallet', models.ForeignKey(help_text='钱包', on_delete=django.db.models.deletion.CASCADE, to='myApp.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='signhistory',
            name='userinfo',
            field=models.ForeignKey(help_text='用户信息', on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='userinfo',
            field=models.ForeignKey(help_text=' 用户信息', on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='questionnairesuggest',
            name='userinfo',
            field=models.ForeignKey(help_text='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='myApp.Questionnaire'),
        ),
        migrations.AddField(
            model_name='point',
            name='userinfo',
            field=models.OneToOneField(help_text='用户信息', on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='answeritem',
            name='item',
            field=models.ForeignKey(help_text='选项', on_delete=django.db.models.deletion.CASCADE, to='myApp.QuestionItem'),
        ),
        migrations.AddField(
            model_name='answeritem',
            name='userinfo',
            field=models.ForeignKey(help_text='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(help_text='问卷', on_delete=django.db.models.deletion.CASCADE, to='myApp.Questionnaire'),
        ),
        migrations.AddField(
            model_name='answer',
            name='userinfo',
            field=models.ForeignKey(help_text='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.UserInfo'),
        ),
    ]
