# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20180522_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriegroup',
            name='categorieId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='childgroup',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.CategorieGroup', to_field='categorieId'),
        ),
    ]
