# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auto_20180524_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isCheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='isOrder',
            field=models.BooleanField(default=True),
        ),
    ]
